### ISSUE TITLE
Sample model and usage for LazyCollection.

### ISSUE THREAD

**Issue by voodookoop** [darxis/EntityFramework.LazyLoading#2]
Hi, could you please provide sample usage for LazyCollection? Tried to change type of a property from ICollection<> to LazyCollection<> and accessing says that "The type of navigation property 'UserGroupRoles' on the entity type 'Role' is 'LazyCollection<UserGroupRole>' for which it was not possible to create a concrete instance. Either initialize the property before use, add a public parameterless constructor to the type, or use a type which can be assigned a HashSet<> or List<>.'" so obviously this is not the good direction. Thanks

**Comment by darxis** [comment]
Hi,

`LazyCollection<>` is an internal type and shouldn't be used in your model, only `LazyReference<>` should be used (until dynamic proxy objects are implemented).

In your model, if you want to define a collection as "lazy-loading ready" you just have to define it like this:
```c#
public class Parent
{
    public ICollection<Child> Childs { get; set; }
}

public class Child
{
    private LazyReference<Parent> _parentLazy = new LazyReference<Parent>();
    public Parent Parent
    {
        get
        {
            return _parentLazy.GetValue(this, nameof(Parent));
        }
        set
        {
            _parentLazy.SetValue(value);
        }
    }
}
```

So basically, you define it like any other collection in EF Core. Additional configuration is required only for single references, not for collections.

The `LazyCollection<>` inherits from `ICollection<>`, and when you will access the `Childs` property, the `LazyCollection<>` will fetch the entities from the DB.

For a working sample please check out the https://github.com/darxis/EntityFramework.LazyLoading/tree/master/samples/Microsoft.EntityFrameworkCore.LazyLoading.Sample directory.

Edit: I have updated the README.md file with this example above which provides better understanding of the configuration required.
